- defaults:
    link:
      create: true
      relink: true

- clean:
    ~/:
      force: true
    ~/.config:
      recursive: true

- link:
    ~/bin/helper-scripts:
      glob: true
      path: config/helper-scripts/*
    # ZSH config
    ~/.zshenv: config/zsh/zshenv
    ~/.zshrc: config/zsh/zshrc
    ~/.config/zsh/p10k.zsh: config/zsh/p10k.zsh
    ~/.config/zsh/p10k-portable.zsh: config/zsh/p10k-portable.zsh

- create:
    - ~/bin
    - ~/bin/helper-scripts

- shell:
    - [touch ~/.z]
    - [pnpm install-completion zsh]
